# Generated by Django 3.2.6 on 2021-09-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapi', '0002_respository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
